import os
import re
import glob

def build_continuity_report():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    chapters_dir = os.path.join(base_dir, "chapters")
    output_file = os.path.join(base_dir, "reference", "story_continuity.md")

    chapter_files = sorted(glob.glob(os.path.join(chapters_dir, "*.md")) + glob.glob(os.path.join(chapters_dir, "*.qmd")))
    # Filter for narrative chapter files
    chapter_files = [f for f in chapter_files if os.path.basename(f)[0].isdigit() or os.path.basename(f).startswith("0")]
    chapter_files.sort()

    entities = {
        "Brynne": {"role": "Fixer (Connection 5, Loyalty 1)", "mentions": []},
        "Vincent": {"role": "Magic Professional (Connection 5, Loyalty 3)", "mentions": []},
        "Hana": {"role": "Wuxing Talismonger / Pop Idol (Connection 6, Loyalty 6)", "mentions": []},
        "Ni Ni Xiaolu": {"role": "Triad Johnson (Connection 3, Loyalty 1)", "mentions": []},
        "Le Tigre": {"role": "Epoch Model (Connection 5, Loyalty 1)", "mentions": []},
        "Claudette": {"role": "Order of the Golden Dawn Librarian (Connection 5, Loyalty 4)", "mentions": []},
        "Whiskey": {"role": "Street Doc (Connection 2, Loyalty 3)", "mentions": []},
        "Guild": {"role": "Guild of Freelance Assets (Conclave C7 L8)", "mentions": []},
        "Coven": {"role": "Shinto/Musok Coven & Spiritual Circle", "mentions": []}
    }

    chapter_summaries = []

    for chap_path in chapter_files:
        chap_name = os.path.basename(chap_path)
        with open(chap_path, "r", encoding="utf-8") as f:
            content = f.read()

        title_match = re.search(r'^#\s+(.+)$', content, re.MULTILINE)
        title = title_match.group(1) if title_match else chap_name

        words = len(re.findall(r'\b\w+\b', content))
        chapter_summaries.append({"filename": chap_name, "title": title, "word_count": words})

        for entity_name in entities:
            matches = len(re.findall(r'\b' + re.escape(entity_name) + r'\b', content, re.IGNORECASE))
            if matches > 0:
                entities[entity_name]["mentions"].append((chap_name, matches))

    # Generate Markdown documentation
    out = []
    out.append("# Story Continuity & Relationship Graph Index")
    out.append("")
    out.append("This document is dynamically generated by `scripts/continuity_engine.py` to index entity appearances, key narrative anchors, and timeline continuity across Velvet's story portfolio.")
    out.append("")
    out.append("---")
    out.append("")
    out.append("## 1. Key Character Contacts & Entity Tracker")
    out.append("")
    out.append("| Entity / Contact | Role & Archetype | Chapter Appearances |")
    out.append("| --- | --- | --- |")

    for entity_name, info in entities.items():
        if info["mentions"]:
            chaps_str = ", ".join([f"[{m[0]}](file:///{os.path.join(chapters_dir, m[0]).replace('\\', '/')}) ({m[1]}x)" for m in info["mentions"]])
        else:
            chaps_str = "None logged in narrative chapters"
        out.append(f"| **{entity_name}** | {info['role']} | {chaps_str} |")

    out.append("")
    out.append("---")
    out.append("")
    out.append("## 2. Anthology Narrative Chapter Index")
    out.append("")
    out.append("| Chapter File | Title | Word Count | Status |")
    out.append("| --- | --- | --- | --- |")

    total_words = 0
    for ch in chapter_summaries:
        total_words += ch["word_count"]
        out.append(f"| [{ch['filename']}](file:///{os.path.join(chapters_dir, ch['filename']).replace('\\', '/')}) | {ch['title']} | {ch['word_count']:,} | Verified |")

    out.append("")
    out.append(f"**Total Anthology Word Count:** {total_words:,} words across {len(chapter_summaries)} chapters.")
    out.append("")

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(out))

    return output_file, len(chapter_summaries), total_words

def main():
    output_file, chap_count, word_count = build_continuity_report()
    print("=" * 65)
    print(" STORY CONTINUITY & RELATIONSHIP GRAPH ENGINE")
    print("=" * 65)
    print(f" Analyzed {chap_count} story chapters.")
    print(f" Total Anthology Word Count: {word_count:,} words.")
    print(f" Generated Continuity Index: {output_file}")
    print("=" * 65)

if __name__ == "__main__":
    main()
